### ISSUE TITLE
Does not appear to work on Ubuntu

### ISSUE THREAD

**Issue by Jakobud** [xavi-/node-copy-paste#56]
I am testing this on Ubuntu 16.04.2 (Virtualbox VM). Does not appear to work. I'm doing this:

```
const copyPaste = require('copy-paste')
copyPaste.copy('some text', function(){
  console.log('done')
})
```

Then when I try to paste anywhere in Ubuntu the text pasted is not `some text` but instead its the previous thing that was copied to the clipboard.

Is this an issue only because it's a virtual machine or are other people having this same problem on actual Linux systems?

**Comment by richie5um** [comment]
Hi, I've just had a copy/paste bug reported against my VSCode extension that uses this package. I think the issue is that 'xclip' - which this package uses on Linux - isn't installed by default on Debian. A quick 'apt-get install xclip' and it started working for me.

Unfortunately, this package didn't seem to report that error to me, so I had to step through the code to workout the issue.

Hope this helps.

**Comment by xavi-** [comment]
Errors are now more aggressively propagated in [`1.5.3`](https://www.npmjs.com/package/copy-paste/v/1.5.3)

**Comment by xavi-** [comment]
Also it'd be recommended to check for errors in the callback:

```js
copyPaste.copy('some text', function(err){
  if (err) throw err;
  console.log('done')
})
```
