### ISSUE TITLE
Please remove sync-exec from package.json

### ISSUE THREAD

**Issue by inadarei** [xavi-/node-copy-paste#61]
Latest version of sync-exec has security vulnerability (and will most likely never be fixed):

- https://nodesecurity.io/advisories/310
- https://github.com/gvarsanyi/sync-exec/issues/17

Even though it is an optional dependency, it still freaks out nodesecurity tests.

The functionality provided by sync-exec has been available natively, and securely since Node 0.12. I hope we can agree that is archaic enough version of Node that support for it can be stopped?

**Comment by dilin-MS** [comment]
Hi, same issue here. `sync-exec` triggers security vulnerability.
```
Vulnerable versions: <= 0.6.2
Patched version: No fix
Affected versions of sync-exec use files located in /tmp/ to buffer command results before returning values. As /tmp/ is almost always set with world readable permissions, this may allow low privilege users on the system to read the results of commands run via sync-exec under a higher privilege user.

There is currently no direct patch for sync-exec, as the child_process.execSync function provided in Node.js v0.12.0 and later provides the same functionality natively.

The best mitigation currently is to update to Node.js v0.12.0 or later, and migrate all uses of sync-exec to child_process.execSync().
```

Could you help remove the `sync-exec` from package.json?

I saw the #64 someone had create a PR but was not merged into the repo. Why?

It does not look like a good idea to use `@type/copy-paste-win32fix` instead of `@type/copy-paste` simply for the optinoal dependecies's causing security alert.

Could you help remove the `sync-exec` from package.json?

**Comment by AndreiSoroka** [comment]
any update?

**Comment by xavi-** [comment]
It's been removed in [`1.5.0`](https://www.npmjs.com/package/copy-paste/v/1.5.0)
